name: Install + Build + Deploy
on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

jobs:
  build-deploy:
    uses: Plyaz-Official/devtools/.github/workflows/pr-checks.yml@main
    secrets: inherit
